package net.markdrew.biblebowl.server.export

import java.io.ByteArrayOutputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

/**
 * Import-ready study exports (docs/gui-redesign.md §5B "Exports"): a Quizlet/Space CSV and a
 * Kahoot spreadsheet. Both are tiny formats, so they're hand-rolled here rather than pulling in a
 * spreadsheet library.
 */

/** One term/definition pair per row for flashcard import (Quizlet, Space, Anki…). */
fun quizletCsv(cards: List<Pair<String, String>>): String =
    cards.joinToString("\n") { (term, definition) -> csvRow(listOf(term, definition)) }

/**
 * A Space-importable CSV (getspace.app): the `Front,Back` header row its importer requires, then one
 * card per row. Unlike [quizletCsv], a definition's real line breaks are kept (RFC 4180 quoted) —
 * Space renders them, along with Markdown emphasis, inside a card.
 */
fun spaceCsv(cards: List<Pair<String, String>>): String =
    "Front,Back\n" + cards.joinToString("\n") { (front, back) ->
        csvRow(listOf(front, back), keepLineBreaks = true)
    }

/**
 * A Quizlet paste-import file: TAB between term and definition, `;` ending each card. Imported with
 * "between term and definition: Tab" and "between cards: Semicolon" on Quizlet's import screen, a
 * definition's real line breaks survive inside the card (newline can't separate cards then).
 */
fun quizletTabbed(cards: List<Pair<String, String>>): String =
    cards.joinToString("\n") { (term, definition) -> "$term\t$definition;" }

/**
 * Re-emits a tab-separated file as CSV, dropping the trailing empty column a trailing tab leaves.
 * The curated study guide is authored as TSV (`StudyGuideParser`); CSV is only its download shape.
 */
fun tsvToCsv(tsv: ByteArray): ByteArray =
    tsv.decodeToString().split('\n').filter { it.isNotBlank() }
        .joinToString("\n") { line -> csvRow(line.split('\t').dropLastWhile { it.isBlank() }) }
        .toByteArray()

/**
 * An RFC 4180 row: fields joined by commas, each quoted only when it needs it. [keepLineBreaks]
 * preserves newlines inside a field (forcing the quotes RFC 4180 then requires) instead of
 * collapsing them for one-line-per-card importers.
 */
private fun csvRow(fields: List<String>, keepLineBreaks: Boolean = false): String =
    fields.joinToString(",") { field ->
        val value =
            if (keepLineBreaks) field.replace("\r\n", "\n").replace(IN_LINE_BREAKERS, " ").trim()
            else field.replace(ROW_BREAKERS, " ").trim()
        if (',' in value || '"' in value || '\n' in value) "\"" + value.replace("\"", "\"\"") + "\"" else value
    }

/** Importers read one card/question per line, so tabs and newlines collapse to spaces in a field. */
private val ROW_BREAKERS = Regex("[\\t\\n\\r]+")

/** What still collapses when line breaks are kept: tabs and stray carriage returns. */
private val IN_LINE_BREAKERS = Regex("[\\t\\r]+")

/**
 * One Kahoot question: 2–4 [answers] with 1-based [correctIndices] into them. Kahoot's template
 * caps questions at 120 characters and answers at 75; [kahootXlsx] enforces both.
 */
data class KahootQuestion(
    val question: String,
    val answers: List<String>,
    val correctIndices: List<Int>,
    val timeLimitSeconds: Int = 20,
)

/**
 * Builds an .xlsx workbook in the layout of Kahoot's official quiz-import template: instructions
 * up top, column headers in row 8, and questions in rows 9+ across columns B–H (question,
 * answers 1–4, time limit, correct answer numbers). Kahoot's importer reads exactly those cells.
 *
 * The workbook is written directly as the OPC zip (an .xlsx is a zip of XML parts) with inline
 * strings — no shared-string table or styles needed for an import file.
 */
fun kahootXlsx(questions: List<KahootQuestion>): ByteArray {
    val rows = StringBuilder()
    // Row 2: template banner (informational only; the importer starts at row 9).
    rows.appendRow(2, listOf("B" to "Kahoot! quiz — generated by Texas Bible Bowl"))
    rows.appendRow(
        8,
        listOf(
            "B" to "Question - max 120 characters",
            "C" to "Answer 1 - max 75 characters",
            "D" to "Answer 2 - max 75 characters",
            "E" to "Answer 3 - max 75 characters",
            "F" to "Answer 4 - max 75 characters",
            "G" to "Time limit (sec) - 5, 10, 20, 30, 60, 90, 120, or 240 secs",
            "H" to "Correct answer(s) - choose at least one",
        ),
    )
    questions.forEachIndexed { i, q ->
        val row = 9 + i
        val cells = buildList {
            add("B" to q.question.take(120))
            q.answers.take(4).forEachIndexed { a, answer -> add(('C' + a).toString() to answer.take(75)) }
            add("H" to q.correctIndices.joinToString(","))
        }
        rows.appendRow(row, cells, numberCells = listOf("G" to q.timeLimitSeconds))
    }

    val sheet = """
        <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
        <worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>$rows</sheetData></worksheet>
    """.trimIndent()

    return zip(
        "[Content_Types].xml" to """
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
            <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
            <Default Extension="xml" ContentType="application/xml"/>
            <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
            <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
            </Types>
        """.trimIndent(),
        "_rels/.rels" to """
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
            <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
            </Relationships>
        """.trimIndent(),
        "xl/workbook.xml" to """
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
            <sheets><sheet name="Sheet1" sheetId="1" r:id="rId1"/></sheets>
            </workbook>
        """.trimIndent(),
        "xl/_rels/workbook.xml.rels" to """
            <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
            <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
            </Relationships>
        """.trimIndent(),
        "xl/worksheets/sheet1.xml" to sheet,
    )
}

/** Appends a `<row>` of inline-string [cells] (column letter to text) plus optional [numberCells]. */
private fun StringBuilder.appendRow(
    row: Int,
    cells: List<Pair<String, String>>,
    numberCells: List<Pair<String, Int>> = emptyList(),
) {
    append("""<row r="$row">""")
    // Emit in column order so the XML stays spec-clean (readers expect ascending cell refs).
    val stringCells = cells.map { (col, text) -> col to (text to true) }
    val numeric = numberCells.map { (col, n) -> col to (n.toString() to false) }
    (stringCells + numeric).sortedBy { it.first }.forEach { (col, cell) ->
        val (value, isString) = cell
        if (isString) {
            append("""<c r="$col$row" t="inlineStr"><is><t xml:space="preserve">${value.xmlEscape()}</t></is></c>""")
        } else {
            append("""<c r="$col$row"><v>$value</v></c>""")
        }
    }
    append("</row>")
}

private fun String.xmlEscape(): String =
    replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        .replace("\"", "&quot;").replace("'", "&apos;")

private fun zip(vararg entries: Pair<String, String>): ByteArray {
    val out = ByteArrayOutputStream()
    ZipOutputStream(out).use { zip ->
        entries.forEach { (name, content) ->
            zip.putNextEntry(ZipEntry(name))
            zip.write(content.toByteArray(Charsets.UTF_8))
            zip.closeEntry()
        }
    }
    return out.toByteArray()
}
